### ISSUE TITLE
Training equipment

### ISSUE THREAD

**Issue by Zeyu1226-mt** [haojc/ShufflingVideosForTSG#1]
Hello, very meaningful work. How many GPUs are needed for the training? How long is it altogether?

**Comment by haojc** [comment]
Both our baseline and our approach are light-weight and efficient. We conduct our experiments on a single NVIDIA 2080ti. And the training process will take about 1 hour for Charades and 3 hours for ANet, respectively.

**Comment by Zeyu1226-mt** [comment]
Thank you very much



发自我的iPhone


------------------ Original ------------------
From: haojc ***@***.***&gt;
Date: Fri,Aug 5,2022 4:41 PM
To: haojc/ShufflingVideosForTSG ***@***.***&gt;
Cc: 习泽宇 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [haojc/ShufflingVideosForTSG] Training equipment (Issue #1)

**Comment by Zeyu1226-mt** [comment]
您好，我是刚接触这个领域，我想问下，这个temporal grounding 和video grounding 是一回事吗



发自我的iPhone


------------------ Original ------------------
From: haojc ***@***.***&gt;
Date: Fri,Aug 5,2022 4:41 PM
To: haojc/ShufflingVideosForTSG ***@***.***&gt;
Cc: 习泽宇 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [haojc/ShufflingVideosForTSG] Training equipment (Issue #1)





 
Both our baseline and our approach are light-weight and efficient. We conduct our experiments on a single NVIDIA 2080ti. And the training process will take about 1 hour for Charades and 3 hours for ANet, respectively.

**Comment by haojc** [comment]
@xzy123456611 这个任务被人们起了很多名字，比如, Temporal sentence grounding, Temporal grounding, Video moment retrieval, Temporal action localization based on language等等。具体还是要根据论文中对任务的描述为准。Video Grounding一般默认指Temporal grounding，但是还有一个任务Spatial-temporal video grounding比Temporal grounding更加细粒度，所以建议使用更准确的名称。

**Comment by Zeyu1226-mt** [comment]
非常感谢您的回复，学到了




习泽宇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "haojc/ShufflingVideosForTSG"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月6日(星期六) 晚上9:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [haojc/ShufflingVideosForTSG] Training equipment (Issue #1)





 
@xzy123456611 这个任务被人们起了很多名字，比如, Temporal sentence grounding, Temporal grounding, Video moment retrieval, Temporal action localization based on language等等。具体还是要根据论文中对任务的描述为准。Video Grounding一般默认指Temporal grounding，但是还有一个任务Spatial-temporal video grounding比Temporal grounding更加细粒度，所以建议使用更准确的名称。
