### ISSUE TITLE
how to generate the word embeddings?

### ISSUE THREAD

**Issue by onlyonewater** [haojc/ShufflingVideosForTSG#10]
hi, authors, how to generate the word embeddings, like ixtoword.npy, word_glove_fts_init.npy, and wordtoix.npy files, could you provide a demo about it? thanks!!!

**Comment by haojc** [comment]
hi, I have updated the raw code I used to generate the word embeddings in this [file](https://github.com/haojc/ShufflingVideosForTSG/blob/main/generate_glove_wordembed.py). You need to download the glove file by yourself. (I am very busy recently and directly update the raw file, so you may need to make some changes to the code to fit your application)

**Comment by onlyonewater** [comment]
ok, thanks! I will have a try!
