### ISSUE TITLE
a little bug in your code???

### ISSUE THREAD

**Issue by onlyonewater** [haojc/ShufflingVideosForTSG#11]
Hi, @haojc , thanks for releasing your code, great work, I found that in your `train.py` file, in the training stage, you used the augmentation data to evaluate the model, but I think it should use the original data to test the model's performance, like the code in your `test.py` file.
https://github.com/haojc/ShufflingVideosForTSG/blob/df562a04424fecfa7f126632d6342f50bb33a81b/grounding/train.py#L209-L247

**Comment by haojc** [comment]
Sry, I don't get the meaning. 
I will try to explain the code you mentioned. During the validation stage, we want to observe both grounding and auxiliary performance, so we input both original and pseudo videos into the pipeline. But the grounding performance is only calculated by the grounding results of the original videos. And the video encoder encodes the original and pseudo videos separately, so the input of pseudo videos will not influence the output of the original videos.

**Comment by onlyonewater** [comment]
ok, thanks for your detailed explanation, I got it, and it seems that Shuffling is a model-independent strategy, using the pseudo video as a counterfactual sample to enforce the model to focus on the video content rather than the location.
