### ISSUE TITLE
Temporal bias

### ISSUE THREAD

**Issue by Zeyu1226-mt** [haojc/ShufflingVideosForTSG#2]
Hello, what does the temporal bias mean?? Thank you very much.

**Comment by haojc** [comment]
Please refer to our [paper](https://arxiv.org/abs/2207.14698) and the papers [BMVC2020](https://www.bmvc2020-conference.com/assets/papers/0306.pdf), [HUMA2021](https://dl.acm.org/doi/abs/10.1145/3475723.3484247), [SIGIR2021](https://arxiv.org/abs/2106.01534), which have the explicit explanation.

**Comment by Zeyu1226-mt** [comment]
OK,Thanks very much









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "haojc/ShufflingVideosForTSG"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月8日(星期一) 中午11:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [haojc/ShufflingVideosForTSG] Temporal bias (Issue #2)





 
Please refer to our paper and the papers BMVC2020, HUMA2021, SIGIR2021, which have the explicit explanation.
