### ISSUE TITLE
missing word_glove_fts_init.npy

### ISSUE THREAD

**Issue by fake-warrior8** [haojc/ShufflingVideosForTSG#6]
Hi, there is a missing word_glove_fts_init_file in the data/ANet/words folder, is this file the same as the one in the data/Charades/words folder?

**Comment by fake-warrior8** [comment]
> Hi, there is a missing word_glove_fts_init_file in the data/ANet/words folder, is this file the same as the one in the data/Charades/words folder?

I found it in the given bbox links.

**Comment by haojc** [comment]
Oh, yes. The word embedding files of anet dataset can be accessed by the cloud links.
